In [1]:
import numpy as np

In [37]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
data

array([[82, 56,  9, 36, 77],
       [ 4,  3, 67, 46, 52],
       [66, 21, 58, 96,  5],
       [25, 10, 23, 49, 16],
       [13, 71, 85, 27,  4]])

In [6]:
#Swap the second and fourth rows of the data matrix.
data[[0,1,2,3,4]] = data[[3,1,2,0,4]]
data

array([[53, 17, 53,  9, 36],
       [26, 74, 19, 86, 77],
       [25, 82, 14,  5, 54],
       [21, 40,  6, 51, 18],
       [29, 57, 54, 42, 43]])

In [10]:
#Normalization
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized_data.round(2)

array([[0.59, 0.15, 0.59, 0.05, 0.38],
       [0.26, 0.85, 0.17, 1.  , 0.89],
       [0.25, 0.95, 0.11, 0.  , 0.6 ],
       [0.2 , 0.43, 0.01, 0.57, 0.16],
       [0.3 , 0.64, 0.6 , 0.46, 0.47]])

In [11]:
# Z-score normalization 
z_score_data = (data - np.mean(data)) / np.std(data)
z_score_data.round(2)

array([[ 0.57, -0.96,  0.57, -1.3 , -0.15],
       [-0.58,  1.45, -0.87,  1.96,  1.58],
       [-0.62,  1.79, -1.09, -1.47,  0.61],
       [-0.79,  0.02, -1.42,  0.48, -0.92],
       [-0.45,  0.74,  0.61,  0.1 ,  0.14]])

In [12]:
# Array splitting - Reshape the data matrix into a vector 
# and split this array into five equal-sized sub-arrays.
sub_arrays = np.split(np.ravel(data), 5)
sub_arrays

[array([53, 17, 53,  9, 36]),
 array([26, 74, 19, 86, 77]),
 array([25, 82, 14,  5, 54]),
 array([21, 40,  6, 51, 18]),
 array([29, 57, 54, 42, 43])]

In [13]:
#Dot product - Create two vectors of size 5 with any values.
# Compute the dot product of the two vectors*.
v1 = np.array([3,5,6,7,8])
v2 = np.array([2,4,6,8,10])
dot_product = np.dot(v1, v2)
dot_product 
# In example there is output = `562` but i don't understand why

198

In [14]:
# Matrix multiplication - Create another 3x3 matrix with any values (let’s call it data2).
# Perform matrix multiplication (dot product of data (first 3x3 part) and data2).
data1 = data[:3, :3]
data2 = np.array([[2, 3, 4],
                  [5, 6, 7],
                  [8, 9, 10]])
res = np.dot(data1, data2)
res

array([[615, 738, 861],
       [574, 693, 812],
       [572, 693, 814]])

In [15]:
#Create a 3x3 identity matrix*, multiply it with 2 and compute its inverse.
matrix5 = np.eye(3)
np.linalg.inv(matrix5*2)

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [ ]:
#Replace random 5 elements in the data matrix with np.nan.
# Find the indices of the missing values.

data = data.astype('float') 
for i in range(6): data[np.random.randint(5), np.random.randint(5)] = np.nan
data

In [35]:
indices = np.nonzero(data)
indices 

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4], dtype=int64))

In [36]:
#  Replace the missing values in the data matrix with the mean of the matrix 
# (ignoring the missing values while computing the mean).
data[np.isnan(data)] = np.nanmean(data)
data

array([[92. , 32. , 47. , 90. , 58. ],
       [72. , 21. , 56. , 26. , 48. ],
       [55.3, 55.3, 55.3, 67. , 87. ],
       [48.5, 55.3, 68. , 48.5, 64. ],
       [55.3, 76. , 48.5,  8. , 48.5]])