In [2]:
import numpy as np

In [3]:
#Create a vector* of zeros with size 10 using np.zeros().
zeros = np.zeros((10), dtype=int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#Compute the memory size* of any array.
zeros.size * zeros.itemsize

40

In [8]:
#Retrieve the documentation of the numpy add function from the command line.
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [11]:
#Create a vector with values ranging from 10 to 49 using np.arange().
new_array = np.arange(10,50)
new_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# Reverse a vector so the first element becomes last

new_array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [13]:
#Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape()
new_matrix = np.arange(0,9).reshape(3,3)
new_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero()
array1 = np.array([1,2,0,0,4,0])
np.nonzero(array1)

(array([0, 1, 4], dtype=int64),)

In [18]:
Create a 3x3 identity matrix* using np.eye().
mtrix1 = np.eye(3)
mtrix1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#Create a 5x5 matrix with row values ranging from 0 to 4. 
#The output should be a matrix where each row is [0, 1, 2, 3, 4].
matrix2 = np.tile(np.arange(5), (5, 1))
matrix2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [24]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded.
array2 = np.linspace(0, 1, 12)[1:11]
array2

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [25]:
#Create a random vector of size 10 and sort it.
array3 = np.random.rand(10)
sorted_array3 = np.sort(array3)
sorted_array3

array([0.01078002, 0.04386508, 0.14900784, 0.23622665, 0.36153156,
       0.37533809, 0.59717787, 0.7186561 , 0.72749617, 0.83094582])

In [36]:
#Print the minimum and maximum representable value for each numpy scalar type* 
#(int8, int32, int64, float32, float64).
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [37]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [38]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [39]:
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [40]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [41]:
#How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype.
float_array = np.array([1.5, 2.7, 3.9], dtype=np.float32)
float_array = float_array.astype(np.int32)
float_array

array([1, 2, 3])

In [50]:
#Subtract the mean* of each row of a matrix.
new_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
row_means = np.mean(new_matrix, axis=1)
row_means

array([1., 4., 7.])

In [60]:
sorted_matrix = new_matrix[new_matrix[:, 1].argsort()[::-1]]
sorted_matrix

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [62]:
#How to swap two rows of an array? You can do this using array indexing.

#I still use new_matrix
row_index1 = 1
row_index2 = 2
new_matrix[[row_index1, row_index2]] = new_matrix[[row_index2, row_index1]]
new_matrix

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [74]:
# Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C?
array4 = np.array([1,2,0,0,4,0,3])
array5 = np.repeat(np.arange(len(array4)), array4)
array5

array([0, 1, 1, 4, 4, 4, 4, 6, 6, 6])

In [75]:
np.bincount(array5)

array([1, 2, 0, 0, 4, 0, 3], dtype=int64)